import { CitizenReport, HazardCase, SensorTelemetry, Shelter, FieldCrew, SystemConfig } from '../types';

export interface WardDefinition {
  id: string;
  name: string;
  polygon: [number, number][]; // lat, lng points
  center: [number, number];
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'EXTREME';
  population: number;
}

export const WARDS: WardDefinition[] = [
  {
    id: 'ward-01',
    name: 'Colombo Central & Fort (Ward 01)',
    center: [6.9344, 79.8428],
    polygon: [
      [6.9450, 79.8350],
      [6.9480, 79.8550],
      [6.9250, 79.8600],
      [6.9200, 79.8380],
    ],
    riskLevel: 'MEDIUM',
    population: 45000,
  },
  {
    id: 'ward-02',
    name: 'Kelani River Basin (Ward 02)',
    center: [6.9580, 79.8900],
    polygon: [
      [6.9750, 79.8700],
      [6.9800, 79.9150],
      [6.9450, 79.9100],
      [6.9400, 79.8650],
    ],
    riskLevel: 'EXTREME',
    population: 82000,
  },
  {
    id: 'ward-03',
    name: 'Kolonnawa Floodplain (Ward 03)',
    center: [6.9300, 79.8950],
    polygon: [
      [6.9450, 79.8750],
      [6.9400, 79.9200],
      [6.9150, 79.9150],
      [6.9200, 79.8700],
    ],
    riskLevel: 'HIGH',
    population: 68000,
  },
  {
    id: 'ward-04',
    name: 'Kaduwela Lowlands (Ward 04)',
    center: [6.9350, 79.9800],
    polygon: [
      [6.9550, 79.9500],
      [6.9600, 80.0100],
      [6.9150, 80.0050],
      [6.9100, 79.9450],
    ],
    riskLevel: 'HIGH',
    population: 54000,
  },
  {
    id: 'ward-05',
    name: 'Wellawatte Canal Corridor (Ward 05)',
    center: [6.8750, 79.8650],
    polygon: [
      [6.8950, 79.8550],
      [6.8900, 79.8850],
      [6.8550, 79.8750],
      [6.8600, 79.8500],
    ],
    riskLevel: 'MEDIUM',
    population: 72000,
  },
  {
    id: 'ward-06',
    name: 'Gampaha Attanagalu Oya Basin',
    center: [7.0917, 79.9997],
    polygon: [
      [7.1200, 79.9700],
      [7.1300, 80.0300],
      [7.0600, 80.0350],
      [7.0550, 79.9650],
    ],
    riskLevel: 'HIGH',
    population: 95000,
  },
  {
    id: 'ward-07',
    name: 'Kalutara Kalu Ganga Basin',
    center: [6.5854, 79.9607],
    polygon: [
      [6.6200, 79.9300],
      [6.6300, 79.9900],
      [6.5500, 80.0000],
      [6.5400, 79.9400],
    ],
    riskLevel: 'HIGH',
    population: 88000,
  },
  {
    id: 'ward-08',
    name: 'Ratnapura Low-Lying Flood Corridor',
    center: [6.6828, 80.4034],
    polygon: [
      [6.7200, 80.3700],
      [6.7300, 80.4400],
      [6.6400, 80.4500],
      [6.6300, 80.3600],
    ],
    riskLevel: 'EXTREME',
    population: 62000,
  },
  {
    id: 'ward-09',
    name: 'Kandy Mahaweli River Basin',
    center: [7.2906, 80.6337],
    polygon: [
      [7.3300, 80.6000],
      [7.3400, 80.6700],
      [7.2500, 80.6800],
      [7.2400, 80.5900],
    ],
    riskLevel: 'MEDIUM',
    population: 110000,
  },
  {
    id: 'ward-10',
    name: 'Galle Gin Ganga Basin',
    center: [6.0535, 80.2210],
    polygon: [
      [6.0900, 80.1900],
      [6.1000, 80.2500],
      [6.0100, 80.2600],
      [6.0000, 80.1800],
    ],
    riskLevel: 'HIGH',
    population: 78000,
  },
];

export const SENSORS: SensorTelemetry[] = [
  {
    stationId: 'sensor-rg-01',
    stationName: 'Fort Harbour Rain Gauge',
    stationType: 'RAIN_GAUGE',
    wardId: 'ward-01',
    lat: 6.9380,
    lng: 79.8450,
    rainfallRateMmH: 42.5,
    rainfallAccumulated3h: 68.0,
    riverLevelMeters: 0,
    riverCapacityPct: 0,
    status: 'WARNING',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rl-02',
    stationName: 'Kelani Ganga Bridge Ultrasonic Sensor',
    stationType: 'RIVER_LEVEL',
    wardId: 'ward-02',
    lat: 6.9620,
    lng: 79.8920,
    rainfallRateMmH: 58.0,
    rainfallAccumulated3h: 112.5,
    riverLevelMeters: 5.85,
    riverCapacityPct: 88.5,
    status: 'DANGER',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rg-03',
    stationName: 'Kolonnawa Marshland Station',
    stationType: 'RAIN_GAUGE',
    wardId: 'ward-03',
    lat: 6.9280,
    lng: 79.8980,
    rainfallRateMmH: 48.0,
    rainfallAccumulated3h: 84.0,
    riverLevelMeters: 3.2,
    riverCapacityPct: 78.0,
    status: 'WARNING',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rl-04',
    stationName: 'Kaduwela Bridge River Depth Monitor',
    stationType: 'RIVER_LEVEL',
    wardId: 'ward-04',
    lat: 6.9360,
    lng: 79.9780,
    rainfallRateMmH: 64.0,
    rainfallAccumulated3h: 130.0,
    riverLevelMeters: 6.10,
    riverCapacityPct: 92.0,
    status: 'DANGER',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rg-05',
    stationName: 'Wellawatte Canal Tidal Gauge',
    stationType: 'RAIN_GAUGE',
    wardId: 'ward-05',
    lat: 6.8720,
    lng: 79.8620,
    rainfallRateMmH: 22.0,
    rainfallAccumulated3h: 38.0,
    riverLevelMeters: 1.8,
    riverCapacityPct: 52.0,
    status: 'NORMAL',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rl-06',
    stationName: 'Attanagalu Oya Gampaha Station',
    stationType: 'RIVER_LEVEL',
    wardId: 'ward-06',
    lat: 7.0950,
    lng: 79.9950,
    rainfallRateMmH: 52.0,
    rainfallAccumulated3h: 96.0,
    riverLevelMeters: 4.80,
    riverCapacityPct: 84.0,
    status: 'DANGER',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rl-07',
    stationName: 'Kalu Ganga Kalutara Estuary Monitor',
    stationType: 'RIVER_LEVEL',
    wardId: 'ward-07',
    lat: 6.5880,
    lng: 79.9650,
    rainfallRateMmH: 45.0,
    rainfallAccumulated3h: 82.0,
    riverLevelMeters: 4.20,
    riverCapacityPct: 80.0,
    status: 'WARNING',
    updatedAt: new Date().toISOString(),
  },
  {
    stationId: 'sensor-rl-08',
    stationName: 'Ratnapura Kalu Ganga Flood Sensor',
    stationType: 'RIVER_LEVEL',
    wardId: 'ward-08',
    lat: 6.6850,
    lng: 80.4050,
    rainfallRateMmH: 72.0,
    rainfallAccumulated3h: 145.0,
    riverLevelMeters: 7.40,
    riverCapacityPct: 96.0,
    status: 'DANGER',
    updatedAt: new Date().toISOString(),
  },
];

export const SHELTERS: Shelter[] = [
  {
    id: 'shelter-01',
    name: 'St. Peter’s College Community Hall',
    wardId: 'ward-05',
    location: {
      lat: 6.8820,
      lng: 79.8580,
      roadName: 'Galle Road (A2)',
      roadHierarchy: 'ARTERIAL_A1',
      wardId: 'ward-05',
      wardName: 'Wellawatte Canal Corridor',
    },
    totalCapacity: 250,
    currentOccupancy: 84,
    isOpen: true,
    supplies: {
      foodPacks: 450,
      waterLitres: 2400,
      medicalKits: 45,
      blankets: 320,
    },
    amenities: ['Emergency Power Generator', 'Medical First Aid Post', 'Wheelchair Ramp', 'Infant Care Station'],
    contactPhone: '+94 11 258 4120',
  },
  {
    id: 'shelter-02',
    name: 'Kelani Maha Vidyalaya Relief Center',
    wardId: 'ward-02',
    location: {
      lat: 6.9650,
      lng: 79.8880,
      roadName: 'Kandy Road Bypass',
      roadHierarchy: 'MAJOR_COLLECTOR',
      wardId: 'ward-02',
      wardName: 'Kelani River Basin',
    },
    totalCapacity: 400,
    currentOccupancy: 360,
    isOpen: true,
    supplies: {
      foodPacks: 120,
      waterLitres: 800,
      medicalKits: 12,
      blankets: 150,
    },
    amenities: ['Rescue Boat Dock', 'High Elevation Floor', 'Drinking Water Purifier'],
    contactPhone: '+94 11 291 3344',
  },
  {
    id: 'shelter-03',
    name: 'Kolonnawa Youth Center Shelter',
    wardId: 'ward-03',
    location: {
      lat: 6.9240,
      lng: 79.8890,
      roadName: 'IDH Hospital Road',
      roadHierarchy: 'MAJOR_COLLECTOR',
      wardId: 'ward-03',
      wardName: 'Kolonnawa Floodplain',
    },
    totalCapacity: 180,
    currentOccupancy: 45,
    isOpen: true,
    supplies: {
      foodPacks: 300,
      waterLitres: 1500,
      medicalKits: 30,
      blankets: 200,
    },
    amenities: ['Pharmacy Link', 'Mobile Kitchen', 'Child Play Area'],
    contactPhone: '+94 11 257 8890',
  },
  {
    id: 'shelter-04',
    name: 'Kaduwela Multipurpose Civic Hall',
    wardId: 'ward-04',
    location: {
      lat: 6.9380,
      lng: 79.9720,
      roadName: 'High Level Link Road',
      roadHierarchy: 'ARTERIAL_A1',
      wardId: 'ward-04',
      wardName: 'Kaduwela Lowlands',
    },
    totalCapacity: 350,
    currentOccupancy: 190,
    isOpen: true,
    supplies: {
      foodPacks: 500,
      waterLitres: 3000,
      medicalKits: 50,
      blankets: 350,
    },
    amenities: ['Helipad Access', 'Heavy Transport Access', 'Solar Backup'],
    contactPhone: '+94 11 254 7711',
  },
  {
    id: 'shelter-05',
    name: 'Ratnapura Ferguson High School Relief Camp',
    wardId: 'ward-08',
    location: {
      lat: 6.6890,
      lng: 80.3980,
      roadName: 'Colombo - Batticaloa Highway (A4)',
      roadHierarchy: 'ARTERIAL_A1',
      wardId: 'ward-08',
      wardName: 'Ratnapura Low-Lying Flood Corridor',
    },
    totalCapacity: 500,
    currentOccupancy: 210,
    isOpen: true,
    supplies: {
      foodPacks: 600,
      waterLitres: 4000,
      medicalKits: 65,
      blankets: 450,
    },
    amenities: ['Medical Hospital Proximity', 'Rescue Boat Storage', 'High Ground Evacuation Hall'],
    contactPhone: '+94 45 222 2234',
  },
];

export const FIELD_CREWS: FieldCrew[] = [
  {
    id: 'crew-01',
    name: 'Rapid Flood Pump Unit 01 (De-watering)',
    specialization: 'WATER_PUMPING',
    currentLocation: { lat: 6.9400, lng: 79.8800 },
    status: 'AVAILABLE',
    contactPhone: '+94 77 123 4561',
  },
  {
    id: 'crew-02',
    name: 'Heavy Chainsaw & Tree Clearance Squad 04',
    specialization: 'TREE_CLEARANCE',
    currentLocation: { lat: 6.9310, lng: 79.8550 },
    status: 'AVAILABLE',
    contactPhone: '+94 77 123 4562',
  },
  {
    id: 'crew-03',
    name: 'Navy Disaster Rescue Boat Squad A',
    specialization: 'RESCUE_BOAT',
    currentLocation: { lat: 6.9600, lng: 79.8900 },
    status: 'DISPATCHED',
    assignedTicketId: 'ticket-01',
    contactPhone: '+94 77 123 4563',
  },
  {
    id: 'crew-04',
    name: 'Municipal Road Repair & Sandbagging Crew 02',
    specialization: 'ROAD_REPAIR',
    currentLocation: { lat: 6.9250, lng: 79.9100 },
    status: 'AVAILABLE',
    contactPhone: '+94 77 123 4564',
  },
  {
    id: 'crew-05',
    name: 'Sabaragamuwa Flash Flood Rescue Unit 03',
    specialization: 'RESCUE_BOAT',
    currentLocation: { lat: 6.6830, lng: 80.4020 },
    status: 'AVAILABLE',
    contactPhone: '+94 77 123 4565',
  },
];

export const INITIAL_CONFIG: SystemConfig = {
  aiConfidenceThreshold: 0.70,
  autoCloseRoadOnCritical: true,
  broadcastRadiusMeters: 1500,
  weatherRainfallDangerMmH: 30.0,
  riverLevelDangerPct: 75.0,
};

export const INITIAL_CASES: HazardCase[] = [
  {
    id: 'case-01',
    reportId: 'rep-init-01',
    source: 'CITIZEN',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    hazardType: 'FLOOD',
    status: 'IN_PROGRESS',
    location: {
      lat: 6.9575,
      lng: 79.8890,
      roadName: 'Kelani Bridge Approach Road (A1)',
      roadHierarchy: 'ARTERIAL_A1',
      wardId: 'ward-02',
      wardName: 'Kelani River Basin',
    },
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
    description: 'Water overflowing from Kelani bank, 3 feet water depth on main road. Buses stalled.',
    roadClosed: true,
    broadcastSent: true,
    ticketId: 'ticket-01',
    nearbyVerifications: [
      { userId: 'user-02', confirmed: true, timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(), note: 'Water is still rising.' },
      { userId: 'user-05', confirmed: true, timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(), note: 'Vehicles cannot cross.' },
    ],
    verdictData: {
      caseId: 'case-01',
      verdict: 'CONFIRMED',
      confidenceScore: 0.96,
      urgency: 'CRITICAL',
      primaryHazard: 'FLOOD',
      checks: {
        image: {
          checkName: 'IMAGE_AI',
          engine: 'AI',
          passed: true,
          score: 0.95,
          summary: 'Detected severe road inundation with stalled vehicles (est. depth 0.9m).',
          details: { detectedHazard: 'FLOOD', depthEstimateMeters: 0.9, validity: 'GENUINE_HAZARD' },
        },
        weather: {
          checkName: 'WEATHER_SYSTEM',
          engine: 'SYSTEM',
          passed: true,
          score: 0.98,
          summary: 'River station at 88.5% capacity and rainfall is 58.0 mm/h (exceeds 30mm/h danger threshold).',
          details: { rainfallMmH: 58.0, riverCapacityPct: 88.5, ruleTriggered: 'HIGH_RIVER_AND_RAINFALL' },
        },
        cluster: {
          checkName: 'CLUSTER_SYSTEM',
          engine: 'SYSTEM',
          passed: true,
          score: 0.92,
          summary: '3 independent citizen reports recorded within 180m over the past 45 minutes.',
          details: { reportsInCluster: 3, radiusMeters: 180 },
        },
        location: {
          checkName: 'LOCATION_AI',
          engine: 'AI',
          passed: true,
          score: 0.94,
          summary: 'Image vegetation, bridge structure, and overcast lighting match Kelani River Basin topography.',
          details: { sceneConsistency: 'HIGH', geographicMatch: true },
        },
        risk: {
          checkName: 'RISK_AI',
          engine: 'AI',
          passed: true,
          score: 0.99,
          summary: 'Arterial Highway A1 carries 4,000 veh/hr; 120m from emergency ambulance depot.',
          details: { roadImpact: 'CRITICAL_ARTERY', populationAtRisk: 'HIGH' },
        },
      },
      reasoningChain: [
        'Image confirms substantial depth disabling heavy vehicular traffic.',
        'Deterministic weather check confirms 88.5% river surge at nearest gauge.',
        'Spatiotemporal cluster check validates 3 corroborating reports.',
        'Critical arterial highway designation requires immediate closure and high-priority rescue dispatch.',
      ],
      recommendedActions: [
        'Close Kelani Bridge Approach Road immediately',
        'Dispatch Navy Rescue Boat Squad A for trapped motorists',
        'Broadcast Ward 02 area alert with detour via Kandy Road Bypass',
      ],
      triggeredOutcomes: ['PUBLISHED', 'AREA_ALERT', 'COUNCIL_TICKET'],
    },
  },
  {
    id: 'case-02',
    reportId: 'rep-init-02',
    source: 'CITIZEN',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    hazardType: 'FALLEN_TREE',
    status: 'VERIFIED',
    location: {
      lat: 6.9320,
      lng: 79.8510,
      roadName: 'Chatham Street / Fort Junction',
      roadHierarchy: 'MAJOR_COLLECTOR',
      wardId: 'ward-01',
      wardName: 'Colombo Central & Fort',
    },
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    description: 'Large banyan tree fallen across both lanes. Power cables snapped.',
    roadClosed: true,
    broadcastSent: true,
    ticketId: 'ticket-02',
    nearbyVerifications: [],
    verdictData: {
      caseId: 'case-02',
      verdict: 'CONFIRMED',
      confidenceScore: 0.89,
      urgency: 'HIGH',
      primaryHazard: 'FALLEN_TREE',
      checks: {
        image: {
          checkName: 'IMAGE_AI',
          engine: 'AI',
          passed: true,
          score: 0.94,
          summary: 'Large fallen tree trunk spanning full 2-lane roadway with downed overhead cables.',
          details: { detectedHazard: 'FALLEN_TREE', blockagePct: 100 },
        },
        weather: {
          checkName: 'WEATHER_SYSTEM',
          engine: 'SYSTEM',
          passed: true,
          score: 0.82,
          summary: 'Fort rain gauge records 42.5 mm/h with sustained wind gusts of 62 km/h.',
          details: { rainfallMmH: 42.5, windGustKmh: 62 },
        },
        cluster: {
          checkName: 'CLUSTER_SYSTEM',
          engine: 'SYSTEM',
          passed: false,
          score: 0.50,
          summary: 'Single report so far; no duplicate reports within 200m.',
          details: { reportsInCluster: 1 },
        },
        location: {
          checkName: 'LOCATION_AI',
          engine: 'AI',
          passed: true,
          score: 0.91,
          summary: 'Colonial architecture and street signage in background matches Chatham Street.',
          details: { sceneConsistency: 'HIGH', geographicMatch: true },
        },
        risk: {
          checkName: 'RISK_AI',
          engine: 'AI',
          passed: true,
          score: 0.88,
          summary: 'Downed power lines present electrocution hazard; blocks key commercial access.',
          details: { roadImpact: 'MAJOR_COLLECTOR', electrocutionRisk: true },
        },
      },
      reasoningChain: [
        'Image clearly reveals 100% road blockage by massive tree trunk and live wires.',
        'High wind gusts (62 km/h) corroborate treefall event in Fort.',
        'Immediate chainsaw squad dispatch required to prevent gridlock.',
      ],
      recommendedActions: [
        'Close Chatham Street between York St and Duke St',
        'Dispatch Chainsaw & Tree Clearance Squad 04',
        'Notify Electricity Board for immediate line disconnection',
      ],
      triggeredOutcomes: ['PUBLISHED', 'AREA_ALERT', 'COUNCIL_TICKET'],
    },
  },
  {
    id: 'case-03',
    reportId: 'rep-init-03',
    source: 'CITIZEN',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    hazardType: 'FLOOD',
    status: 'VERIFIED',
    location: {
      lat: 6.6840,
      lng: 80.4040,
      roadName: 'Ratnapura Main Bazaar Road (A4)',
      roadHierarchy: 'ARTERIAL_A1',
      wardId: 'ward-08',
      wardName: 'Ratnapura Low-Lying Flood Corridor',
    },
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
    description: 'Kalu Ganga spill water reached commercial district, 4ft depth.',
    roadClosed: true,
    broadcastSent: true,
    ticketId: undefined,
    nearbyVerifications: [],
    verdictData: {
      caseId: 'case-03',
      verdict: 'CONFIRMED',
      confidenceScore: 0.97,
      urgency: 'CRITICAL',
      primaryHazard: 'FLOOD',
      checks: {
        image: { checkName: 'IMAGE_AI', engine: 'AI', passed: true, score: 0.96, summary: 'Submerged shopfronts and road in Ratnapura bazaar.', details: {} },
        weather: { checkName: 'WEATHER_SYSTEM', engine: 'SYSTEM', passed: true, score: 0.99, summary: 'Kalu Ganga sensor at 96% danger crest with 72mm/h downpour.', details: {} },
        cluster: { checkName: 'CLUSTER_SYSTEM', engine: 'SYSTEM', passed: true, score: 0.90, summary: 'Multiple reports from Sabaragamuwa chamber.', details: {} },
        location: { checkName: 'LOCATION_AI', engine: 'AI', passed: true, score: 0.95, summary: 'Matches Ratnapura riverfront topography.', details: {} },
        risk: { checkName: 'RISK_AI', engine: 'AI', passed: true, score: 0.98, summary: 'Critical A4 highway blocked; major relief center at risk.', details: {} },
      },
      reasoningChain: [
        'Kalu Ganga river crest at 96% confirms major flood event.',
        'High commercial density and stranded residents require immediate boat deployment.',
      ],
      recommendedActions: [
        'Close A4 Highway through Ratnapura Bazaar',
        'Dispatch Sabaragamuwa Flash Flood Rescue Unit 03',
      ],
      triggeredOutcomes: ['PUBLISHED', 'AREA_ALERT', 'COUNCIL_TICKET'],
    },
  },
];
